# Misc.
alias clearbashhist="cat /dev/null > ~/.bash_history && history -c && exit"
alias clearnvimswap="rm ~/.local/state/nvim/swap/*.swp"
alias sshk="kitty +kitten ssh"
alias mm="micromamba"
alias n="nvim"
alias nn="nvim --clean"
alias sn="sudoedit"
alias ta="tmux a -t"
alias updatenvim="wget -O /tmp/nvim.appimage https://github.com/neovim/neovim/releases/download/stable/nvim.appimage && mv /tmp/nvim.appimage ~/bin/nvim && chmod u+x ~/bin/nvim"

# Podman
alias pm="podman"
alias pma="podman attach"
alias pmc="podman container"
alias pme="podman exec"
alias pmi="podman image"
alias pmp="podman pull"
alias pmr="podman run"
alias pmv="podman volume"
alias pmcom="podman-compose"
alias svc="systemctl --user"
alias svc-logs="journalctl --user -u"
alias svc-reload="systemctl --user daemon-reload"
alias svc-restart="systemctl --user restart"
alias svc-start="systemctl --user start"
alias svc-status="systemctl --user status"
alias svc-stop="systemctl --user stop"

# LSD
alias l="lsd -lFh"
alias la="lsd -lAFh"
alias lr="lsd -tRFh"
alias lt="lsd -ltFh"
alias ll="lsd -l"
alias ldot="lsd -ld .*"
alias lS="lsd -1FSsh"
alias lart="lsd -1Fcart"
alias lrt="lsd -1Fcrt"
alias lsr="lsd -lARFh"
alias lsn="lsd -1"
