model: gemini
weak-model: gemini_flash
alias:
  - "gpt4o:openrouter/gpt-4o"
  - "claude37:anthropic/claude-3-7-sonnet-20250219"
  - "claude37_or:openrouter/anthropic/claude-3.7-sonnet"
  - "gemini:gemini/gemini-2.5-pro-preview-05-06"
  - "gemini_flash:gemini/gemini-2.5-flash-preview-04-17"
# diff-fenced for gemini models, diff for others
# https://aider.chat/docs/more/edit-formats.html
edit-format: diff-fenced
suggest-shell-commands: false
map-tokens: 0
auto-commits: false
code-theme: one-dark
vim: true
editor: nvim
