model: g
weak-model: gf
alias:
  - "c37:anthropic/claude-3-7-sonnet-20250219"
  - "c37_or:openrouter/anthropic/claude-3.7-sonnet"
  - "c40:anthropic/claude-sonnet-4-20250514"
  - "g:gemini/gemini-2.5-pro"
  - "gf:gemini/gemini-2.5-flash"
  - "gl:gemini/gemini-2.5-flash-lite-preview-06-17"
  - "gpt4o:openrouter/gpt-4o"
# diff-fenced for gemini models, diff for others
# https://aider.chat/docs/more/edit-formats.html
edit-format: diff-fenced
suggest-shell-commands: false
map-tokens: 0
auto-commits: false
code-theme: one-dark
vim: true
editor: nvim
